### ISSUE TITLE
[ENHANCEMENT] Better visualization of encrypted data like a video

### ISSUE THREAD

**Issue by mak626** [werbhq/schello#19]
Right now to show the authencity of our encryption.
We are showing the live data from database.

We want to show this in a better manner as recommended by panel like a video or something.

![Image](https://user-images.githubusercontent.com/60577077/222972588-e53f4876-79af-4a2a-8dad-440d4af5c9ba.png)

Looking for some animation/art showing how their data is processed.  A visual video might be good

**Comment by navaneethvenu** [comment]
Prototype done. Close it once recording is complete.

**Comment by mak626** [comment]
@karthikasankar2000 I have added the video at `src\pages\DrugReport\DrugReportForm.tsx` 
Please style it nicely like width height to align with the page

`< CardMedia component="video" image={ReportVideo} autoPlay />`

Refer the branch `report-video-visualization`
